fields:
  - description
keywords:
  - abattoir
  - animal
  - bull
  - canine
  - cat
  - cattle
  - chicken
  - cow
  - dog
  - duck
  - farm
  - feline
  - geese
  - goat
  - goose
  - hen
  - kitten
  - livestock
  - pig
  - poultry
  - puppies
  - puppy
  - swine
  - turkey
  - fish
  - lamb
  - sheep
  - veal
  - fishery

  # Below optained from https://www.mla.com.au/general/glossary/#glossarySection_A

  - agent # Sells and buys cattle on behalf of clients
  - AuctionsPlus # Internet based livestock auction system
  - bobby 
  - calf 
  - backgrounder # A cattle producer who produces young cattle ready for lot feeding
  - blue tag # A tail tag on a cow at a physical market
  - boning room # Area of an abattoir where the carcase is cut into smaller portions
  - beef 
  - carcase
  - CL # Chemical lean
  - chemical lean
  - conditioning
  - crossbred
  - crossbreeding
  - CWE # Carcase weight equivalent
  - CWT # Carcase weight
  - dam # Mother of a particular calf
  - damara # South African fat-tailed meat breed of sheep
  - $/head # Dollars per head of lives stock. Units by which cattle are sold at store sale.
  - DCW # Dressed carcase weight
  - DWT # Dressed weight
  - ewe # Female sheep with more than two permanent teeth
  - EYCI # Eastern Young Cattle Indicator, used as a general cattle market benchmark
  - fat score # Measure of fat cover across an animal's ribs and rump
  - feeders
  - feedlot
  - grainfed
  - grassfed
  - grazier # A farmer which raises livestock such as sheep or cattle
  - mutton
  - heifer
  - HGP # Hormone growth promotant
  - hogget # Castrated male and female sheep with no 'ram like' characteristics and up to two permanent teeth.
  - ox
  - killing # Killing floor, etc etc
  - LWT # Liveweight - the weight of a live animal
  - LMO # Livestock market officer
  - longfed # An animal that is grainfed, in a feedlot, for an extended period of time.
  - lotfed
  - MSA # Meat Standars Australia
  - Meatworks
  - MLA # Meat and Livestock Australia
  - NLIS # National Livestock Identification System
  - NLRS # National Livestock Reporting Service
  - NSM # Non-station mated - refers to when a cow or heifer has not been intentionally exposed to a bull
  - OTH # Over the hooks - refers to the marketing of cattle/sheep/lambs directly from the farm to an abattoir where a producer is paid for the value of the carcase based on a sliding grid
  - pastoralist
  - PTIC # Pregnancy tested in calf
  - PTNIC # Pregnancy tested not in calf
  - ram
  - saleyard
  - second-cross # The breed developed by mating a meat breed ram with a first-cross ewe
  - shortfed
  - slaughter
  - steer
  - yardings # Number of cattle offered for sale at a saleyard auction
  - yearling # Young animal, fully weaned without permanent incisor teeth